#!/usr/bin/env python
import sys
from numpy import *
from vtk import *

fn = "../STL/TetFrameFINAL.STL"

if __name__ == "__main__":
    
    ####### is the point inside? #######
    
    ## read in STL
    reader = vtkSTLReader()
    reader.SetFileName(fn)
    reader.Update()
    
    shape3d = reader.GetOutput()
    print shape3d.GetNumberOfPoints(), "points in STL"
    
    bounds = shape3d.GetBounds()
    
    ## set up points to check
    points = vtkPoints()
    
    for i in range(100):
        x = random.uniform(low=bounds[0], high=bounds[1])
        y = random.uniform(low=bounds[2], high=bounds[3])
        z = random.uniform(low=bounds[4], high=bounds[5])
        points.InsertNextPoint([x,y,z])
    
    checkPoints = vtkPolyData()
    checkPoints.SetPoints(points)
    
    ## set up vtk point checker
    pointChecker = vtkSelectEnclosedPoints()
    pointChecker.SetInput(checkPoints)
    pointChecker.SetSurface(shape3d)
    pointChecker.Update()
    
    ## output
    inout = []
    
    inPoints0 = vtkPoints()
    outPoints0 = vtkPoints()
    
    for i in range(checkPoints.GetNumberOfPoints()):
        inout.append(pointChecker.IsInside(i))
        print i, inout[-1]
        if inout[-1]:
            inPoints0.InsertNextPoint(points.GetPoint(i))
        else:
            outPoints0.InsertNextPoint(points.GetPoint(i))
            
    inPoints = vtkPolyData()
    inPoints.SetPoints(inPoints0)
    outPoints = vtkPolyData()
    outPoints.SetPoints(outPoints0)
    
    ####### rendering to verify #######
    
    ## shape mapper, actor
    shapeMapper = vtkPolyDataMapper()
    shapeMapper.SetInputConnection(reader.GetOutputPort())

    shapeActor = vtkActor()
    shapeActor.SetMapper(shapeMapper)
    shapeActor.GetProperty().SetOpacity(0.5)
    
    ## point mappers, actors
    inverteces = vtkVertexGlyphFilter()
    inverteces.AddInput(inPoints)
    inverteces.Update()
    
    inpointsMapper = vtkPolyDataMapper()
    inpointsMapper.SetInputConnection(inverteces.GetOutputPort())
    
    inpointsActor = vtkActor()
    inpointsActor.SetMapper(inpointsMapper)
    inpointsActor.GetProperty().SetPointSize(5)
    inpointsActor.GetProperty().SetColor(0, 0, 1)
    
    outverteces = vtkVertexGlyphFilter()
    outverteces.AddInput(outPoints)
    outverteces.Update()
    
    outpointsMapper = vtkPolyDataMapper()
    outpointsMapper.SetInputConnection(outverteces.GetOutputPort())
    
    outpointsActor = vtkActor()
    outpointsActor.SetMapper(outpointsMapper)
    outpointsActor.GetProperty().SetPointSize(5)
    outpointsActor.GetProperty().SetColor(1, 0, 0)
    
    ## renderer, render window, interactor
    renderer = vtkRenderer()
    renderWindow = vtkRenderWindow()
    interactor = vtkRenderWindowInteractor()
    
    renderWindow.AddRenderer(renderer)
    interactor.SetRenderWindow(renderWindow)
    
    ## add actors
    renderer.AddActor(shapeActor)
    renderer.AddActor(inpointsActor)
    renderer.AddActor(outpointsActor)
    renderer.SetBackground(0,0,0)
    
    renderWindow.SetWindowName("testSTLPoints")
    renderWindow.Render()
    interactor.Start();
        