#!/usr/bin/env python
#
# example of simple usage of sharpy to load a surface
# and test points
#
# make sure to add sharpy directory to your PYTHONPATH
#
###########################################################
from __future__ import division
import sys
from numpy import *

from sharpy.shape3d import Shape3D

# fn = "../STL/dolo.STL"
N = 1000

if __name__ == "__main__":
    
    fn = sys.argv[1]
    
    ## Load STL
    sh = Shape3D(fn)
    
    ## create random set of points to check
    pointlist = []
    
    print 'sampling ' + str(N) + ' points'
    for i in range(N):
        x = random.uniform(low=sh._bounds[0], high=sh._bounds[1])
        y = random.uniform(low=sh._bounds[2], high=sh._bounds[3])
        z = random.uniform(low=sh._bounds[4], high=sh._bounds[5])
        pointlist.append([x,y,z])
    
    
    # check and visualize
    inside = sh.is_inside(pointlist)
    sh.visualize()
    